"""add relationship between Board and Card

Revision ID: 437db2ca769d
Revises: 118994d64111
Create Date: 2023-06-27 11:35:52.907871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '437db2ca769d'
down_revision = '118994d64111'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('board_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'card', 'board', ['board_id'], ['board_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_column('card', 'board_id')
    # ### end Alembic commands ###
